baseURL = "https://knz.cx/"
languageCode = "en-us"
title = "knz.cx"
theme = "hyde"
enableEmoji = true
relativeURLs = true
summaryLength = 20

[params]
  themeColor = "theme-base-0d"
  description = "devops • docker • linux"

[mediaTypes]
[mediaTypes."text/markdown"]
suffixes = ["md"]

[outputFormats]
  [outputFormats.MD]
    baseName = 'index'
    isPlainText = true
    mediaType = 'text/markdown'

[outputs]
  page = ['HTML', 'MD']
  section = ['HTML', 'MD', 'RSS']
  term = ['HTML', 'MD', 'RSS']
  taxonomy = ['HTML', 'MD', 'RSS']
  links = ['HTML', 'MD', 'RSS']
